#include "syntax_gen.h"

VocabEntry vocab_table[] = {
    { "a", VOCAB_BUZZ, NULL },
    { "an", VOCAB_BUZZ, NULL },
    { "the", VOCAB_BUZZ, NULL },
    { "is", VOCAB_BUZZ, NULL },
    { "are", VOCAB_BUZZ, NULL },
    { "equals", VOCAB_BUZZ, NULL },
    { "<synonym", VOCAB_BUZZ, NULL },
    { "with", VOCAB_BUZZ, NULL },
    { "using", VOCAB_BUZZ, NULL },
    { "through", VOCAB_BUZZ, NULL },
    { "thru", VOCAB_BUZZ, NULL },
    { "inside", VOCAB_SYNONYM, "in" },
    { "into", VOCAB_SYNONYM, "in" },
    { "both", VOCAB_SYNONYM, "all" },
    { "onto", VOCAB_SYNONYM, "on" },
    { "above", VOCAB_SYNONYM, "over" },
    { "n", VOCAB_SYNONYM, "north" },
    { "fore", VOCAB_SYNONYM, "north" },
    { "forward", VOCAB_SYNONYM, "north" },
    { "foreward", VOCAB_SYNONYM, "north" },
    { "f", VOCAB_SYNONYM, "north" },
    { "s", VOCAB_SYNONYM, "south" },
    { "aft", VOCAB_SYNONYM, "south" },
    { "e", VOCAB_SYNONYM, "east" },
    { "cw", VOCAB_SYNONYM, "east" },
    { "starboard", VOCAB_SYNONYM, "east" },
    { "sb", VOCAB_SYNONYM, "east" },
    { "w", VOCAB_SYNONYM, "west" },
    { "ccw", VOCAB_SYNONYM, "west" },
    { "port", VOCAB_SYNONYM, "west" },
    { "p", VOCAB_SYNONYM, "west" },
    { "d", VOCAB_SYNONYM, "down" },
    { "u", VOCAB_SYNONYM, "up" },
    { "brief", VOCAB_VERB, NULL },
    { "super", VOCAB_VERB, NULL },
    { "superbrief", VOCAB_SYNONYM, "super" },
    { "diagnose", VOCAB_VERB, NULL },
    { "inventory", VOCAB_VERB, NULL },
    { "i", VOCAB_SYNONYM, "inventory" },
    { "quit", VOCAB_VERB, NULL },
    { "q", VOCAB_SYNONYM, "quit" },
    { "restar", VOCAB_VERB, NULL },
    { "restor", VOCAB_VERB, NULL },
    { "save", VOCAB_VERB, NULL },
    { "score", VOCAB_VERB, NULL },
    { "script", VOCAB_VERB, NULL },
    { "unscript", VOCAB_VERB, NULL },
    { "$verify", VOCAB_VERB, NULL },
    { "version", VOCAB_VERB, NULL },
    { "verbose", VOCAB_VERB, NULL },
    { "#random", VOCAB_VERB, NULL },
    { "#command", VOCAB_VERB, NULL },
    { "#record", VOCAB_VERB, NULL },
    { "#unrecord", VOCAB_VERB, NULL },
    { "again", VOCAB_VERB, NULL },
    { "g", VOCAB_SYNONYM, "again" },
    { "answer", VOCAB_VERB, NULL },
    { "reply", VOCAB_SYNONYM, "answer" },
    { "apply", VOCAB_VERB, NULL },
    { "to", VOCAB_PREP, NULL },
    { "attack", VOCAB_VERB, NULL },
    { "fight", VOCAB_SYNONYM, "attack" },
    { "hurt", VOCAB_SYNONYM, "attack" },
    { "injure", VOCAB_SYNONYM, "attack" },
    { "hit", VOCAB_SYNONYM, "attack" },
    { "kill", VOCAB_SYNONYM, "attack" },
    { "murder", VOCAB_SYNONYM, "attack" },
    { "slay", VOCAB_SYNONYM, "attack" },
    { "dispatch", VOCAB_SYNONYM, "attack" },
    { "board", VOCAB_VERB, NULL },
    { "climb", VOCAB_VERB, NULL },
    { "on", VOCAB_PREP, NULL },
    { "up", VOCAB_PREP, NULL },
    { "down", VOCAB_PREP, NULL },
    { "in", VOCAB_PREP, NULL },
    { "sit", VOCAB_VERB, NULL },
    { "under", VOCAB_PREP, NULL },
    { "over", VOCAB_PREP, NULL },
    { "near", VOCAB_PREP, NULL },
    { "across", VOCAB_PREP, NULL },
    { "recline", VOCAB_SYNONYM, "sit" },
    { "lie", VOCAB_SYNONYM, "sit" },
    { "lay", VOCAB_SYNONYM, "sit" },
    { "stand", VOCAB_VERB, NULL },
    { "close", VOCAB_VERB, NULL },
    { "collapse", VOCAB_SYNONYM, "close" },
    { "fold", VOCAB_SYNONYM, "close" },
    { "shorten", VOCAB_SYNONYM, "close" },
    { "curse", VOCAB_VERB, NULL },
    { "damn", VOCAB_SYNONYM, "curse" },
    { "shit", VOCAB_SYNONYM, "curse" },
    { "fuck", VOCAB_SYNONYM, "curse" },
    { "trot", VOCAB_SYNONYM, "curse" },
    { "krip", VOCAB_SYNONYM, "curse" },
    { "megakrip", VOCAB_SYNONYM, "curse" },
    { "trotting", VOCAB_SYNONYM, "curse" },
    { "disembark", VOCAB_VERB, NULL },
    { "drop", VOCAB_VERB, NULL },
    { "release", VOCAB_SYNONYM, "drop" },
    { "eat", VOCAB_VERB, NULL },
    { "from", VOCAB_PREP, NULL },
    { "drink", VOCAB_SYNONYM, "eat" },
    { "swallow", VOCAB_SYNONYM, "eat" },
    { "enter", VOCAB_VERB, NULL },
    { "exit", VOCAB_VERB, NULL },
    { "examine", VOCAB_VERB, NULL },
    { "describe", VOCAB_SYNONYM, "examine" },
    { "what", VOCAB_SYNONYM, "examine" },
    { "whats", VOCAB_SYNONYM, "examine" },
    { "find", VOCAB_VERB, NULL },
    { "where", VOCAB_SYNONYM, "find" },
    { "seek", VOCAB_SYNONYM, "find" },
    { "see", VOCAB_SYNONYM, "find" },
    { "fire", VOCAB_VERB, NULL },
    { "at", VOCAB_PREP, NULL },
    { "zap", VOCAB_SYNONYM, "fire" },
    { "blast", VOCAB_SYNONYM, "fire" },
    { "shoot", VOCAB_SYNONYM, "fire" },
    { "burn", VOCAB_SYNONYM, "fire" },
    { "follow", VOCAB_VERB, NULL },
    { "pursue", VOCAB_SYNONYM, "follow" },
    { "chase", VOCAB_SYNONYM, "follow" },
    { "flush", VOCAB_VERB, NULL },
    { "fly", VOCAB_VERB, NULL },
    { "give", VOCAB_VERB, NULL },
    { "hand", VOCAB_SYNONYM, "give" },
    { "donate", VOCAB_SYNONYM, "give" },
    { "offer", VOCAB_SYNONYM, "give" },
    { "feed", VOCAB_SYNONYM, "give" },
    { "hello", VOCAB_VERB, NULL },
    { "hi", VOCAB_SYNONYM, "hello" },
    { "help", VOCAB_VERB, NULL },
    { "hint", VOCAB_SYNONYM, "help" },
    { "hints", VOCAB_SYNONYM, "help" },
    { "jump", VOCAB_VERB, NULL },
    { "off", VOCAB_PREP, NULL },
    { "leap", VOCAB_SYNONYM, "jump" },
    { "kick", VOCAB_VERB, NULL },
    { "kiss", VOCAB_VERB, NULL },
    { "knock", VOCAB_VERB, NULL },
    { "rap", VOCAB_SYNONYM, "knock" },
    { "leave", VOCAB_VERB, NULL },
    { "listen", VOCAB_VERB, NULL },
    { "lock", VOCAB_VERB, NULL },
    { "look", VOCAB_VERB, NULL },
    { "around", VOCAB_PREP, NULL },
    { "behind", VOCAB_PREP, NULL },
    { "out", VOCAB_PREP, NULL },
    { "for", VOCAB_PREP, NULL },
    { "l", VOCAB_SYNONYM, "look" },
    { "stare", VOCAB_SYNONYM, "look" },
    { "gaze", VOCAB_SYNONYM, "look" },
    { "search", VOCAB_VERB, NULL },
    { "rummage", VOCAB_SYNONYM, "search" },
    { "sort", VOCAB_SYNONYM, "search" },
    { "sift", VOCAB_SYNONYM, "search" },
    { "move", VOCAB_VERB, NULL },
    { "point", VOCAB_VERB, NULL },
    { "gesture", VOCAB_SYNONYM, "point" },
    { "aim", VOCAB_SYNONYM, "point" },
    { "pull", VOCAB_VERB, NULL },
    { "tug", VOCAB_SYNONYM, "pull" },
    { "destroy", VOCAB_VERB, NULL },
    { "damage", VOCAB_SYNONYM, "destroy" },
    { "break", VOCAB_SYNONYM, "destroy" },
    { "smash", VOCAB_SYNONYM, "destroy" },
    { "open", VOCAB_VERB, NULL },
    { "extend", VOCAB_SYNONYM, "open" },
    { "unfold", VOCAB_SYNONYM, "open" },
    { "lengthen", VOCAB_SYNONYM, "open" },
    { "pick", VOCAB_VERB, NULL },
    { "play", VOCAB_VERB, NULL },
    { "push", VOCAB_VERB, NULL },
    { "against", VOCAB_PREP, NULL },
    { "press", VOCAB_SYNONYM, "push" },
    { "put", VOCAB_VERB, NULL },
    { "stuff", VOCAB_SYNONYM, "put" },
    { "insert", VOCAB_SYNONYM, "put" },
    { "place", VOCAB_SYNONYM, "put" },
    { "rape", VOCAB_VERB, NULL },
    { "molest", VOCAB_SYNONYM, "rape" },
    { "reach", VOCAB_VERB, NULL },
    { "read", VOCAB_VERB, NULL },
    { "skim", VOCAB_SYNONYM, "read" },
    { "rub", VOCAB_VERB, NULL },
    { "touch", VOCAB_SYNONYM, "rub" },
    { "feel", VOCAB_SYNONYM, "rub" },
    { "pat", VOCAB_SYNONYM, "rub" },
    { "pet", VOCAB_SYNONYM, "rub" },
    { "scrub", VOCAB_VERB, NULL },
    { "swab", VOCAB_SYNONYM, "scrub" },
    { "polish", VOCAB_SYNONYM, "scrub" },
    { "clean", VOCAB_SYNONYM, "scrub" },
    { "shine", VOCAB_SYNONYM, "scrub" },
    { "mop", VOCAB_SYNONYM, "scrub" },
    { "brush", VOCAB_SYNONYM, "scrub" },
    { "sleep", VOCAB_VERB, NULL },
    { "shake", VOCAB_VERB, NULL },
    { "slide", VOCAB_VERB, NULL },
    { "swing", VOCAB_SYNONYM, "slide" },
    { "skip", VOCAB_VERB, NULL },
    { "hop", VOCAB_SYNONYM, "skip" },
    { "smell", VOCAB_VERB, NULL },
    { "sniff", VOCAB_SYNONYM, "smell" },
    { "step", VOCAB_VERB, NULL },
    { "strike", VOCAB_VERB, NULL },
    { "swim", VOCAB_VERB, NULL },
    { "bathe", VOCAB_SYNONYM, "swim" },
    { "wade", VOCAB_SYNONYM, "swim" },
    { "take", VOCAB_VERB, NULL },
    { "get", VOCAB_SYNONYM, "take" },
    { "hold", VOCAB_SYNONYM, "take" },
    { "carry", VOCAB_SYNONYM, "take" },
    { "remove", VOCAB_VERB, NULL },
    { "tell", VOCAB_VERB, NULL },
    { "ask", VOCAB_SYNONYM, "tell" },
    { "smile", VOCAB_VERB, NULL },
    { "grin", VOCAB_SYNONYM, "smile" },
    { "salute", VOCAB_VERB, NULL },
    { "say", VOCAB_VERB, NULL },
    { "talk", VOCAB_SYNONYM, "say" },
    { "throw", VOCAB_VERB, NULL },
    { "hurl", VOCAB_SYNONYM, "throw" },
    { "chuck", VOCAB_SYNONYM, "throw" },
    { "toss", VOCAB_SYNONYM, "throw" },
    { "turn", VOCAB_VERB, NULL },
    { "set", VOCAB_SYNONYM, "turn" },
    { "activate", VOCAB_VERB, NULL },
    { "type", VOCAB_VERB, NULL },
    { "unlock", VOCAB_VERB, NULL },
    { "wait", VOCAB_VERB, NULL },
    { "z", VOCAB_SYNONYM, "wait" },
    { "wake", VOCAB_VERB, NULL },
    { "awake", VOCAB_SYNONYM, "wake" },
    { "surprise", VOCAB_SYNONYM, "wake" },
    { "startle", VOCAB_SYNONYM, "wake" },
    { "walk", VOCAB_VERB, NULL },
    { "go", VOCAB_SYNONYM, "walk" },
    { "run", VOCAB_SYNONYM, "walk" },
    { "proceed", VOCAB_SYNONYM, "walk" },
    { "wave", VOCAB_VERB, NULL },
    { "brandish", VOCAB_SYNONYM, "wave" },
    { "wear", VOCAB_VERB, NULL },
    { "yell", VOCAB_VERB, NULL },
    { "scream", VOCAB_SYNONYM, "yell" },
    { "shout", VOCAB_SYNONYM, "yell" },
    { "zork", VOCAB_VERB, NULL },
    { "sneeze", VOCAB_SYNONYM, "zork" },
    { "yes", VOCAB_VERB, NULL },
    { "y", VOCAB_SYNONYM, "yes" },
    { "affirmative", VOCAB_SYNONYM, "yes" },
    { "no", VOCAB_VERB, NULL },
    { "negative", VOCAB_SYNONYM, "no" },
    { "maybe", VOCAB_VERB, NULL },
    { "possibly", VOCAB_SYNONYM, "maybe" },
    { "dunno", VOCAB_SYNONYM, "maybe" },
    { "pour", VOCAB_VERB, NULL },
    { "spill", VOCAB_SYNONYM, "pour" },
    { "empty", VOCAB_VERB, NULL },
    { "attract", VOCAB_VERB, NULL },
    { "fix", VOCAB_VERB, NULL },
    { "repair", VOCAB_SYNONYM, "fix" },
    { "oil", VOCAB_VERB, NULL },
    { "lubricate", VOCAB_SYNONYM, "oil" },
    { "show", VOCAB_VERB, NULL },
    { "taste", VOCAB_VERB, NULL },
    { "escape", VOCAB_VERB, NULL },
    { "time", VOCAB_VERB, NULL },
    { "t", VOCAB_SYNONYM, "time" },
    { "scold", VOCAB_VERB, NULL },
};
int vocab_table_size = 270;

SyntaxEntry syntax_table[] = {
    { "brief", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_BRIEF },
    { "super", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SUPER_BRIEF },
    { "diagnose", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_DIAGNOSE },
    { "inventory", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_INVENTORY },
    { "quit", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_QUIT },
    { "restar", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_RESTART },
    { "restor", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_RESTORE },
    { "save", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SAVE },
    { "score", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SCORE },
    { "script", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SCRIPT },
    { "unscript", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_UNSCRIPT },
    { "$verify", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_$VERIFY },
    { "$verify", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_$VERIFY },
    { "version", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_VERSION },
    { "verbose", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_VERBOSE },
    { "#random", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_$RANDOM },
    { "#command", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_$COMMAND },
    { "#record", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_$RECORD },
    { "#unrecord", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_$UNRECORD },
    { "again", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_AGAIN },
    { "answer", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_ANSWER },
    { "answer", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_REPLY },
    { "apply", "to", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_PUT },
    { "attack", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_ACTORBIT, 0, V_ATTACK },
    { "attack", "with", NULL, 1, 1, 2, 0, 0, SEARCH_HELD, 0, 0, V_ATTACK },
    { "board", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_VEHBIT, 0, V_BOARD },
    { "climb", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_GO_UP },
    { "climb", "on", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_CLIMBBIT, 0, V_CLIMB_ON },
    { "climb", "up", NULL, 1, 0, 1, 0, 0, 0, F_MUNGBIT, 0, V_CLIMB_UP },
    { "climb", "to", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_CLIMB_UP },
    { "climb", "with", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_THROUGH },
    { "climb", "down", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_CLIMBBIT, 0, V_CLIMB_DOWN },
    { "climb", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_CLIMBBIT, 0, V_CLIMB_FOO },
    { "climb", "in", NULL, 1, 0, 1, 0, SEARCH_ROOM, 0, 0, 0, V_BOARD },
    { "sit", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SIT },
    { "sit", "on", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_VEHBIT, 0, V_CLIMB_ON },
    { "sit", "down", NULL, 1, 0, 1, 0, 0, 0, F_MUNGBIT, 0, V_SIT_DOWN },
    { "sit", "in", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_VEHBIT, 0, V_BOARD },
    { "sit", "in", NULL, 1, 1, 2, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD | PARSE_TRY_TAKE, 0, 0, 0, V_PUT },
    { "sit", "under", NULL, 1, 1, 2, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD | PARSE_TRY_TAKE, 0, 0, 0, V_PUT_UNDER },
    { "sit", "over", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "sit", "near", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "sit", "across", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_SPAN },
    { "stand", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_STAND },
    { "stand", "up", NULL, 1, 0, 1, 0, 0, 0, F_MUNGBIT, 0, V_STAND },
    { "stand", "on", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_STAND_ON },
    { "close", NULL, NULL, 1, 0, 0, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM, 0, 0, 0, V_CLOSE },
    { "curse", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_CURSE },
    { "disembark", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_MUNGBIT, 0, V_DISEMBARK },
    { "drop", NULL, NULL, 1, 0, 0, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD, 0, 0, 0, V_DROP },
    { "drop", "down", NULL, 1, 1, 2, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD, 0, 0, 0, V_PUT },
    { "drop", "in", NULL, 1, 1, 2, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD, 0, 0, 0, V_PUT },
    { "drop", "on", NULL, 1, 1, 2, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD, 0, 0, 0, V_PUT_ON },
    { "eat", NULL, NULL, 1, 0, 0, 0, PARSE_TRY_TAKE, 0, F_FOODBIT, 0, V_EAT },
    { "eat", "from", NULL, 1, 0, 1, 0, PARSE_TRY_TAKE, 0, 0, 0, V_EAT_FROM },
    { "enter", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_ENTER },
    { "enter", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_THROUGH },
    { "exit", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_EXIT },
    { "exit", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_EXIT },
    { "examine", NULL, NULL, 1, 0, 0, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM | PARSE_MANY, 0, 0, 0, V_EXAMINE },
    { "examine", "in", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_ROOM | SEARCH_GROUND | PARSE_MANY, 0, 0, 0, V_LOOK_INSIDE },
    { "examine", "on", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_ROOM | SEARCH_GROUND | PARSE_MANY, 0, 0, 0, V_LOOK_INSIDE },
    { "find", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_FIND },
    { "fire", "with", NULL, 1, 1, 2, 0, 0, SEARCH_HELD, 0, 0, V_SZAP },
    { "fire", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_ZAP },
    { "fire", "at", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_ZAP },
    { "fire", "at", NULL, 1, 1, 2, 0, SEARCH_HELD, 0, 0, 0, V_ZAP },
    { "follow", NULL, NULL, 1, 0, 0, 0, 0, 0, F_ACTORBIT, 0, V_FOLLOW },
    { "flush", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_FLUSH },
    { "fly", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_FLY },
    { "fly", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_FLY },
    { "give", "to", NULL, 1, 1, 2, 0, PARSE_MANY | SEARCH_HELD | SEARCH_HELD, 0, 0, F_ACTORBIT, V_GIVE },
    { "give", NULL, NULL, 1, 1, 0, 0, SEARCH_GROUND, PARSE_MANY | SEARCH_HELD | SEARCH_HELD, F_ACTORBIT, 0, V_SGIVE },
    { "hello", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_HELLO },
    { "hello", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_HELLO },
    { "help", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_HELP },
    { "jump", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_LEAP },
    { "jump", "over", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LEAP },
    { "jump", "across", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LEAP },
    { "jump", "in", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LEAP },
    { "jump", "from", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LEAP },
    { "jump", "off", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LEAP },
    { "kick", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_KICK },
    { "kiss", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_ACTORBIT, 0, V_KISS },
    { "knock", "at", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_KNOCK },
    { "knock", "on", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_KNOCK },
    { "knock", "down", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_ACTORBIT, 0, V_ATTACK },
    { "leave", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_LEAVE },
    { "leave", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_DROP },
    { "listen", "to", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LISTEN },
    { "lock", "with", NULL, 1, 1, 2, 0, SEARCH_GROUND | SEARCH_ROOM, SEARCH_HELD, 0, 0, V_LOCK },
    { "look", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_LOOK },
    { "look", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_LOOK_CRETIN },
    { "look", "around", NULL, 1, 0, 1, 0, 0, 0, F_MUNGBIT, 0, V_LOOK },
    { "look", "at", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM | PARSE_MANY, 0, 0, 0, V_EXAMINE },
    { "look", "on", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM | PARSE_MANY, 0, 0, 0, V_EXAMINE },
    { "look", "with", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LOOK_INSIDE },
    { "look", "under", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LOOK_UNDER },
    { "look", "behind", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_LOOK_BEHIND },
    { "look", "in", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM | PARSE_MANY, 0, 0, 0, V_LOOK_INSIDE },
    { "look", "out", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM | PARSE_MANY, 0, 0, 0, V_LOOK_INSIDE },
    { "look", "for", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_FIND },
    { "look", "down", NULL, 1, 0, 1, 0, 0, 0, F_MUNGBIT, 0, V_LOOK_DOWN },
    { "search", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_SEARCH },
    { "search", "in", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_SEARCH },
    { "search", "for", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_FIND },
    { "search", "with", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_SEARCH },
    { "move", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, 0, 0, V_MOVE },
    { "move", "up", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH_UP },
    { "move", "down", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH_DOWN },
    { "point", "at", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, 0, 0, V_POINT },
    { "point", "to", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, 0, 0, V_POINT },
    { "point", "at", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, SEARCH_GROUND | SEARCH_ROOM, 0, 0, V_POINT },
    { "pull", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_PULL },
    { "pull", "down", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH_DOWN },
    { "pull", "up", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH_UP },
    { "pull", "on", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PULL },
    { "pull", "with", NULL, 1, 1, 2, 0, 0, PARSE_TRY_TAKE, 0, 0, V_ZATTRACT },
    { "destroy", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_MUNG },
    { "destroy", "with", NULL, 1, 1, 2, 0, SEARCH_GROUND | SEARCH_ROOM | SEARCH_HELD | SEARCH_HELD, SEARCH_HELD, 0, 0, V_MUNG },
    { "destroy", "down", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_MUNG },
    { "open", NULL, NULL, 1, 0, 0, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM, 0, 0, 0, V_OPEN },
    { "open", "up", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM, 0, 0, 0, V_OPEN },
    { "open", "with", NULL, 1, 1, 2, 0, 0, SEARCH_HELD, 0, 0, V_OPEN_WITH },
    { "pick", "up", NULL, 1, 0, 1, 0, SEARCH_GROUND | PARSE_MANY, 0, F_TAKEBIT, 0, V_TAKE },
    { "pick", "up", "with", 1, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, V_ZATTRACT },
    { "play", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_PLAY },
    { "play", "with", NULL, 1, 0, 1, 0, 0, 0, F_ACTORBIT, 0, V_PLAY_WITH },
    { "play", "with", NULL, 1, 1, 2, 0, 0, 0, 0, F_ACTORBIT, V_PLAY },
    { "push", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_PUSH },
    { "push", "on", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH },
    { "push", "off", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH },
    { "push", "against", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH },
    { "push", "up", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH_UP },
    { "push", "down", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_PUSH_DOWN },
    { "push", "under", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_PUT_UNDER },
    { "put", "in", NULL, 1, 1, 2, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD | PARSE_TRY_TAKE, 0, 0, 0, V_PUT },
    { "put", "on", NULL, 1, 1, 2, 0, SEARCH_HELD | PARSE_MANY, 0, 0, 0, V_PUT_ON },
    { "put", "down", NULL, 1, 0, 1, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD, 0, 0, 0, V_DROP },
    { "put", "under", NULL, 1, 1, 2, 0, SEARCH_HELD | PARSE_MANY | SEARCH_HELD | PARSE_TRY_TAKE, 0, 0, 0, V_PUT_UNDER },
    { "put", "on", NULL, 1, 0, 1, 0, SEARCH_HELD | PARSE_TRY_TAKE, 0, 0, 0, V_WEAR },
    { "put", "over", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "put", "near", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "put", "across", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_SPAN },
    { "put", "with", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_SLIDE },
    { "put", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_INSERT },
    { "rape", NULL, NULL, 1, 0, 0, 0, 0, 0, F_ACTORBIT, 0, V_RAPE },
    { "reach", "in", NULL, 1, 0, 1, 0, 0, 0, F_CONTBIT, 0, V_REACH },
    { "reach", "for", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_REACH_FOR },
    { "read", NULL, NULL, 1, 0, 0, 0, PARSE_TRY_TAKE, 0, F_READBIT, 0, V_READ },
    { "rub", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_RUB },
    { "rub", "with", NULL, 1, 1, 2, 0, 0, PARSE_TRY_TAKE, 0, 0, V_ZATTRACT },
    { "rub", "to", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "scrub", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_SCRUB },
    { "scrub", "up", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_SCRUB },
    { "scrub", "with", NULL, 1, 1, 2, 0, 0, SEARCH_HELD, 0, 0, V_SCRUB },
    { "sleep", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SLEEP },
    { "shake", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_SHAKE },
    { "shake", "with", NULL, 1, 1, 2, 0, 0, 0, 0, F_ACTORBIT, V_SHAKE_WITH },
    { "slide", "under", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_PUT_UNDER },
    { "slide", "with", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_SLIDE },
    { "slide", "across", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_SPAN },
    { "skip", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SKIP },
    { "smell", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_SMELL },
    { "step", "on", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_STEP_ON },
    { "step", "in", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_STEP_ON },
    { "strike", "with", NULL, 1, 1, 2, 0, SEARCH_GROUND | SEARCH_ROOM, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM | SEARCH_HELD, F_ACTORBIT, 0, V_ATTACK },
    { "strike", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_ACTORBIT, 0, V_ATTACK },
    { "swim", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SWIM },
    { "swim", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_SWIM_DIR },
    { "swim", "to", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_SWIM_DIR },
    { "swim", "in", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_SWIM },
    { "swim", "up", NULL, 1, 0, 1, 0, 0, 0, F_MUNGBIT, 0, V_SWIM_UP },
    { "swim", "down", NULL, 1, 0, 1, 0, 0, 0, F_MUNGBIT, 0, V_SWIM_DIR },
    { "take", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | PARSE_MANY, 0, F_TAKEBIT, 0, V_TAKE },
    { "take", "in", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_VEHBIT, 0, V_BOARD },
    { "take", "out", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_MUNGBIT, 0, V_DISEMBARK },
    { "take", "on", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_VEHBIT, 0, V_CLIMB_ON },
    { "take", "out", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_ROOM, 0, F_TAKEBIT, 0, V_TAKE },
    { "take", "off", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_ROOM, 0, F_TAKEBIT, 0, V_TAKE },
    { "take", "from", NULL, 1, 1, 2, 0, PARSE_MANY | SEARCH_ROOM | SEARCH_HELD, SEARCH_GROUND | SEARCH_HELD, F_TAKEBIT, 0, V_TAKE },
    { "take", "off", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | PARSE_MANY, 0, F_WEARBIT, 0, V_TAKE_OFF },
    { "take", "up", NULL, 1, 0, 1, 0, 0, 0, F_MUNGBIT, 0, V_STAND },
    { "take", "over", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "take", "near", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "take", "with", NULL, 1, 1, 2, 0, 0, PARSE_TRY_TAKE, 0, 0, V_ZATTRACT },
    { "remove", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_REMOVE },
    { "remove", "from", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_TAKE },
    { "remove", "with", NULL, 1, 1, 2, 0, 0, PARSE_TRY_TAKE, 0, 0, V_ZATTRACT },
    { "tell", NULL, NULL, 1, 0, 0, 0, SEARCH_ROOM, 0, F_ACTORBIT, 0, V_TELL },
    { "tell", "for", NULL, 1, 1, 2, 0, SEARCH_ROOM, 0, F_ACTORBIT, 0, V_ASK_FOR },
    { "smile", "at", NULL, 1, 0, 1, 0, 0, 0, F_ACTORBIT, 0, V_SMILE },
    { "smile", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SMILE },
    { "salute", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_SALUTE },
    { "say", "to", NULL, 1, 0, 1, 0, SEARCH_ROOM, 0, F_ACTORBIT, 0, V_TALK },
    { "say", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_SAY },
    { "throw", "at", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, SEARCH_GROUND | SEARCH_ROOM, 0, 0, V_THROW },
    { "throw", "with", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, SEARCH_GROUND | SEARCH_ROOM, 0, 0, V_THROW },
    { "throw", "off", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_THROW_OFF },
    { "throw", "in", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_PUT },
    { "throw", "on", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_PUT },
    { "throw", "over", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_THROW_OFF },
    { "throw", NULL, NULL, 1, 0, 0, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_THROW },
    { "turn", "with", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM, SEARCH_GROUND | SEARCH_ROOM | SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, V_TURN },
    { "turn", "on", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM, 0, F_LIGHTBIT, 0, V_LAMP_ON },
    { "turn", "off", NULL, 1, 0, 1, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM, 0, F_LIGHTBIT, 0, V_LAMP_OFF },
    { "turn", "to", NULL, 1, 1, 2, 0, SEARCH_GROUND | SEARCH_ROOM, 0, 0, 0, V_SET },
    { "turn", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, 0, 0, V_SET },
    { "activate", NULL, NULL, 1, 0, 0, 0, 0, 0, F_LIGHTBIT, 0, V_LAMP_ON },
    { "type", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_TYPE },
    { "type", "in", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_TYPE },
    { "unlock", "with", NULL, 1, 1, 2, 0, SEARCH_GROUND | SEARCH_ROOM, SEARCH_HELD | SEARCH_HELD | SEARCH_GROUND | SEARCH_ROOM | PARSE_TRY_TAKE, 0, F_TOOLBIT, V_UNLOCK },
    { "wait", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_WAIT },
    { "wake", NULL, NULL, 1, 0, 0, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_ACTORBIT, 0, V_ALARM },
    { "wake", "up", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_ACTORBIT, 0, V_ALARM },
    { "walk", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_WALK },
    { "walk", "in", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_THROUGH },
    { "walk", "with", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_THROUGH },
    { "walk", "around", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_WALK_AROUND },
    { "walk", "up", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_CLIMBBIT, 0, V_CLIMB_UP },
    { "walk", "down", NULL, 1, 0, 1, 0, SEARCH_GROUND | SEARCH_ROOM, 0, F_CLIMBBIT, 0, V_CLIMB_DOWN },
    { "walk", "to", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_WALK_TO },
    { "walk", "out", NULL, 1, 0, 1, 0, 0, 0, 0, 0, V_EXIT },
    { "walk", "with", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_SLIDE },
    { "wave", NULL, NULL, 1, 0, 0, 0, SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_WAVE },
    { "wave", "at", NULL, 1, 1, 2, 0, SEARCH_HELD | SEARCH_HELD, 0, 0, 0, V_WAVE },
    { "wave", "over", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "wave", "near", NULL, 1, 1, 2, 0, PARSE_TRY_TAKE, 0, 0, 0, V_ATTRACT },
    { "wear", NULL, NULL, 1, 0, 0, 0, SEARCH_HELD | PARSE_TRY_TAKE, 0, 0, 0, V_WEAR },
    { "yell", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_YELL },
    { "yell", "at", NULL, 1, 0, 1, 0, 0, 0, F_ACTORBIT, 0, V_SCOLD },
    { "zork", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_ZORK },
    { "yes", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_YES },
    { "yes", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_YES },
    { "no", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_NO },
    { "maybe", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_MAYBE },
    { "z", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_ESCAPE },
    { "pour", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_POUR },
    { "pour", "over", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_POUR },
    { "pour", "on", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_POUR },
    { "pour", "out", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_POUR },
    { "pour", "in", NULL, 1, 1, 2, 0, 0, 0, 0, 0, V_POUR },
    { "empty", NULL, NULL, 1, 0, 0, 0, SEARCH_HELD, 0, 0, 0, V_EMPTY },
    { "empty", "in", NULL, 1, 1, 2, 0, SEARCH_HELD, 0, 0, 0, V_EMPTY },
    { "attract", "with", NULL, 1, 1, 2, 0, 0, PARSE_TRY_TAKE, 0, 0, V_ZATTRACT },
    { "fix", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_FIX_IT },
    { "oil", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_OIL },
    { "oil", "with", NULL, 1, 1, 2, 0, 0, SEARCH_HELD, 0, 0, V_OIL },
    { "show", "to", NULL, 1, 1, 2, 0, SEARCH_HELD, 0, 0, F_ACTORBIT, V_SHOW },
    { "taste", NULL, NULL, 1, 0, 0, 0, 0, 0, 0, 0, V_TASTE },
    { "escape", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_ZESCAPE },
    { "time", NULL, NULL, 0, 0, 0, 0, 0, 0, 0, 0, V_TIME },
    { "scold", NULL, NULL, 1, 0, 0, 0, 0, 0, F_ACTORBIT, 0, V_SCOLD },
};
int syntax_table_size = 253;
